

import json
import pprint

EXCLUDE = [
    'GO!', '100 BULLETS', 'KEV', 'ADAM STRANGE', 'AMERICAN CARNAGE', 'AMERICAN VAMPIRE', 'AMERICAN SPLENDOR', 'AMETHYST', 'ANARKY', 'ANIMA', 'ANIMAL MAN', 'ARION', 'ART OPS', 'AZRAEL', 'AZTEK', 'BACKLASH', 'BARDA', 'BLACK ADAM', 'BLACK MAGIC', 'BLACK ORCHID', 'BLACKHAWK', 'BLOOD & SHADOWS', 'BLOOD SYNDICATE', 'BLOODLINES', 'BOOKS OF MAGIC', 'CINDER & ASHE', 'CITY BOY','CLEAN ROOM', 'CHUCK', 'CHASE',' COFFIN HILL', 'COLLAPSER', 'DMZ', 'DUO', 'DV8', 'DAMAGE', 'DANGER STREET', 'DAPHNE DYRNE', 'DEADENDERS', 'DEADMAN', 'DEMON KNIGHTS', 'DESTINY', 'DIAL H', 'DOG MOON', 'VOODOO CHILD', 'ETERNITY GIRL', 'EL DIABLO', 'ELECTRIC WARRIORS', 'EVENT LEVIATHAN', 'EVERAFTER', 'EX MACHINA', 'EXIT STAGE LEFT', 'FBP', 'FABLES', 'FAULT LINES', 'FURIES', 'FIRE', 'FIRE & ICE', 'FLINCH', 'FOREVER PEOPLE', 'FREEDOM FIGHTERS', 'FRINGE', 'FROSTBITE', 'GI COMBAT', 'GALAXY', 'GANGLAND', 'GEN13', 'GET JIRO!', 'GHOSTDANCING', 'GHOSTS', 'GODDESS', 'GODZILLA', 'GLOBAL FREQUENCY', 'HARDWARE', 'HARLEEN', 'HBO MAX', 'H-E-R-O', 'HEART THROBS', 'HELLBLAZER', 'HEX', 'HITMAN', 'HOURMAN', 'HOUSE OF', 'HUMAN BOMB', 'HUMAN DEFENSE CORPS', 'HUMAN TARGET', 'I AM NOT STARFIRE', 'I, VAMPIRE', 'ICON', 'INFERNO', 'INFERIOR FIVE', 'INVASION!', 'JINNY HEX', 'JEW GANGSTER', 'JIMMY OLSEN', 'JINX', 'JOE KUBERT PRESENTS', 'JOE' 'JONAH HEX', 'JONNI THUNDER', 'JONNY DOUBLE', 'JUNK CULTURE', 'JUST IMAGINE', 'JUSTICE LEAGUE:DREAM GIRLS', 'KATANA', 'KID ETERNITY', 'KAMANDI:', 'KLARION', 'KNIGHT & SQUIRE', 'LEGION', 'LOBO', 'MAD', 'LUCIFER', 'MERA', 'METAL MEN', 'MILK WARS', 'NATHANIEL DUSK', "NEIL GAIMAN'S", 'NEIL GAIMAN', 'NEMESIS', 'NEW GODS', 'NEW CHALLENGERS', 'NIGHT FORCE', 'NORTH 40', 'NUBIA:', 'OMAC', 'NUMBER OF THE BEAST', 'ORBITER', 'ORION', 'PHANTOM LADY', 'PLASTIC MAN', 'POWER GIRL', 'PREZ', 'PREACHER', 'PRIMER', 'PROMETHEA', 'QUARANTINE ZONE', 'REBELS', 'RAGMAN', 'RANN-THANAGAR', 'RED THORN', 'RED TORNADO', 'REIGN IN HELL', 'RICHARD DRAGON', 'REVOLVER', 'RONIN', 'ROGUES', 'RORSCHACH', 'SALVATION RUN', 'SASQUATCH', 'SCALPED', 'SAVAGE THINGS', 'SCARAB', 'SCOOBY', 'SEVEN SOLDIERS', 'SHADE,', 'SHADOWPACT', 'SHERIFF OF BABYLON', 'SHOWCASE', 'SIX DAYS', 'SKIN GRAFT', 'SLEEPER', 'SLASH & BURN', 'SOLO', 'STRANGE ADVENTURES', 'SUN DEVILS', 'SURVIVORS CLUB', 'THUNDER AGENTS', 'SWEET TOOTH', 'SWORD OF AZRAEL', 'SWORD OF SORCERY', 'TANGENT COMICS', 'TEAM 7', 'TATTERED BANNERS', 'TEAM ONE WILDC.A.T.S', 'TEAM ZERO', 'TERRA OBSCURA', 'THE AUTHORITY', 'THE DEADMAN', 'THE DARKSTARS', 'THE DARK AND BLOODY', 'THE DEAD BOY DETECTIVES', 'THE DEMON', 'THE DREAMING', 'THE DOLLHOUSE', 'THE EZRA CAIN MYSTERIES', 'THE FILTH', 'THE GIRL WHO WOULD BE DEATH', 'THE GREAT TEN', 'THE KITCHEN', 'THE KAMANDI CHALLENGE', 'THE LEGION', 'THE LITERALS', 'THE LITTLE ENDLESS STORYBOOK', 'THE LOSERS', 'THE LOST BOYS', 'THE MOVEMENT', 'THE MULTIVERSITY', 'THE NAMES OF MAGIC', 'THE NEW DEADWARDIANS','THE NEW GODS', 'THE OMAC PROJECT', 'THE OMEGA MEN', 'THE ORACLE CODE', 'THE RAY', 'THE TRENCHCOAT BRIGADE', 'THE TWILIGHT CHILDREN', 'THE UN-MEN', 'THE UNEXPECTED', 'THE UNWRITTEN', 'THE VIGIL', 'THE WAKE', 'THE WANDERERS', 'THE WILD STORM', 'THE WITCHING', 'TIME WARP', 'TIME MASTERS', 'TIMBER WOLF', 'TOM STRONG', 'TOP 10', 'TORSO', 'TRANSMETROPOLITAN', 'TRILLIUM', 'TRIGGER', 'TRINITY OF SIN', 'TRUTH AND JUSTICE', 'TWO STEP', 'UNCLE SAM', 'UNEARTHED', 'UNDERWORLD UNLEASHED', 'V FOR VENDETTA', 'VALOR', 'VAMPS', 'VERTIGO', 'VICTOR AND NORA', 'VICTORIAN UNDEAD', 'VIXEN', 'VOODOO', 'WACKY RACELAND', 'WALLER VS. WILDSTORM', 'WARRIORS AND A WEE WONDER', 'WEIRD WESTERN TALES', 'WEIRD WAR TALES', 'WEIRD MYSTERY TALES', 'HOUSE OF MYSTERY', 'WELCOME TO TRANQUILITY', 'WETWORKS', 'WHISTLE', 'WHIZ COMICS', "WHO'S WHO", 'WILD DOG', 'WILDC.A.T.S', 'WILDCORE', 'WILDSTORM', 'WITCHCRAFT']

with open(r'backend\preprocesses\dc_series_raw.json') as f:
    data = json.load(f)



series = []
excluded = []

for record in data:
    name = record['az_sort']
    if any(term in name.upper() for term in EXCLUDE):
        excluded.append(name)
        continue
    series.append(name)

print(f"Kept: {len(series)}  |  Excluded: {len(excluded)}")

with open('backend/all_comic_series.json', 'w') as f:
    json.dump(sorted(series), f, indent=2)

